from ollama import Client

from studycopilot.config import settings


client = Client(
    host=settings.ollama_host,
)


def generate(
    prompt: str,
    temperature: float = 0.2,
) -> str:
    """
    Send a prompt to the LLM.

    Parameters
    ----------
    prompt:
        Prompt sent to the model.

    temperature:
        Controls randomness.

    Returns
    -------
    Raw text generated by the model.
    """

    response = client.chat(
        model=settings.llm_model,
        messages=[
            {
                "role": "user",
                "content": prompt,
            }
        ],
        options={
            "temperature": temperature,
        },
    )

    return response["message"]["content"]